In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1


array([1, 2, 3])

In [4]:
# Returns the type of the array which in numpy is always ndarrays-nthdimensionalarray
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a2.dtype
a2.shape


(2, 3)

In [7]:
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
# Outputs the shape
a3.shape 

(3, 2, 3)

In [9]:
#Returns the number of dimensions 
a1.ndim,a2.ndim

(1, 2)

In [10]:
#If it's dtype is an int32 then it will return 4Bytes
# itemsize returns the size of each element in terms of bytes
a1.itemsize
a1.dtype

dtype('int32')

In [11]:
#Returns the number of elements
a1.size

3

In [12]:
import pandas as pd

In [13]:
a2dataframe = pd.DataFrame(a2)
a2dataframe
a2dataframe = pd.DataFrame(a2,columns=['a','b','c'])
a2dataframe

a  b  c
0  1  2  3
1  4  5  6

# creating arrays

### in first section we created arrays ourselves here we will create through different built in methods

In [14]:
sample_array = np.array([1,2,3])
sample_array


array([1, 2, 3])

In [15]:
# to see docs hold tab + shift

In [16]:
ones_array = np.ones((2,3),dtype=int)
ones_array


array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
ones_array.dtype


dtype('int32')

In [18]:
# returns specified size's array filled with zero
zeros = np.zeros((2,3))

In [19]:
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# to generate numbers with even spaces
aranged = np.arange(0,10,3)
aranged

array([0, 3, 6, 9])

In [21]:
# returns specified size's uninitialised values array
emptied = np.empty((1,2))
emptied

array([[-1.35830440e-055,  6.01410209e+153]])

In [22]:
# to generate random numbers low is inclusive while high is exclusive
random_array = np.random.randint(0,100,size =(4,5))
random_array


array([[86, 57, 26, 24,  3],
       [56, 15, 94, 86, 45],
       [21, 45, 94, 94, 60],
       [73, 51, 97,  2, 16]])

In [23]:
random_2 = np.random.rand(2,4)
random_2

array([[0.0205604 , 0.24587361, 0.00427348, 0.80172715],
       [0.53171093, 0.91371357, 0.137295  , 0.66063526]])

In [24]:
random_3 = np.random.random((2,4))
random_3

array([[0.10015949, 0.49554361, 0.28985575, 0.1387493 ],
       [0.91907831, 0.59791695, 0.4717296 , 0.49417911]])

## difference between random and rand is 
Both functions generate samples from the uniform distribution on [0, 1). The only difference is in how the arguments are handled. With numpy.random.rand, the length of each dimension of the output array is a separate argument. 
With numpy.random.random, the shape argument is a single tuple.

In [25]:
# There is a new api to generate random numbers
random_4 = np.random.default_rng()
random_4.random(size = 3)


array([0.89124884, 0.63274361, 0.84677954])

In [26]:
#Returns only the unique values in an array
unique_values = np.unique(zeros)

In [27]:
unique_values


array([0.])

In [28]:
np.unique(ones_array)

array([1])

In [29]:
a4 =np.array([[1,2,3],
      [1,2,3]])
a4

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
np.unique(a4)

array([1, 2, 3])

In [31]:
a5 = np.array(["a","b","b","c","d","a","c"])

In [32]:
a5


array(['a', 'b', 'b', 'c', 'd', 'a', 'c'], dtype='<U1')

In [33]:
values,indice=np.unique(a5,return_index=True)

In [34]:
values


array(['a', 'b', 'c', 'd'], dtype='<U1')

In [35]:
indice

array([0, 1, 3, 4], dtype=int64)

In [36]:
#with random seed you get same values instead of random numbers appearing.

In [37]:
np.random.seed(0)
np.random.randint(10,size=5)

array([5, 0, 3, 3, 7])

In [38]:
#with random seed not set to a particular value this line of code when run multiple times will show diiferent results
np.random.randint(10,size=5)

array([9, 3, 5, 2, 4])

# Viewing Arrays

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [40]:
a3.shape

(3, 2, 3)

In [41]:
#slicing in numpy is same as in python
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [42]:
a6 = np.random.randint(10,size=(2,3,4,5))
a6

array([[[[7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0]],

        [[2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0]],

        [[0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2]]],


       [[[0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1]],

        [[5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7]],

        [[2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6]]]])

In [43]:
a6.shape


(2, 3, 4, 5)

In [44]:
#select first 4 elements of all dimensions
a6[:2,:3,:4,:4]

array([[[[7, 6, 8, 8],
         [6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5]],

        [[2, 3, 8, 1],
         [3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2]],

        [[0, 4, 5, 5],
         [8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7]]],


       [[[0, 3, 5, 9],
         [4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0]],

        [[5, 9, 3, 0],
         [0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2]],

        [[2, 9, 2, 3],
         [2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0]]]])

## Manipulating Arrays

In [45]:
a1


array([1, 2, 3])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a1+a2

array([[2, 4, 6],
       [5, 7, 9]])

In [48]:
a2-a1

array([[0, 0, 0],
       [3, 3, 3]])

In [49]:
a1-a2


array([[ 0,  0,  0],
       [-3, -3, -3]])

In [50]:
a2*a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [52]:
a2.shape,a3.shape

((2, 3), (3, 2, 3))

In [53]:
a2*a3

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

## Broadcasting Rules
### their trails are equal, 
### or one of them is 1

In [54]:
a7 = np.random.randint(20,size=(2,3,3))

In [55]:
a7

array([[[ 0,  6, 19],
        [14, 10, 19],
        [ 8, 13,  2]],

       [[ 3,  2, 11],
        [13, 16,  8],
        [ 8, 19,  8]]])

In [56]:
a7

array([[[ 0,  6, 19],
        [14, 10, 19],
        [ 8, 13,  2]],

       [[ 3,  2, 11],
        [13, 16,  8],
        [ 8, 19,  8]]])

In [57]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a2[:,np.newaxis]*a7

array([[[ 0, 12, 57],
        [14, 20, 57],
        [ 8, 26,  6]],

       [[12, 10, 66],
        [52, 80, 48],
        [32, 95, 48]]])

In [59]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [60]:
#Returns the quotient
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [61]:
#Modulus function returns the remainder
a2 % a1

array([[0, 0, 0],
       [0, 1, 0]], dtype=int32)

In [62]:
#Equivalent of a1+a2 returns addition of arguments element wise
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [63]:
#returns exponents of a1 that is e^(r1c1)
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [64]:
#returns log of argument
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [65]:
#returns powers of a1's elements 
a1**2

array([1, 4, 9], dtype=int32)

In [66]:
#same but through a built in function
np.square(a1)

array([1, 4, 9], dtype=int32)

In [67]:
a1

array([1, 2, 3])

## Aggregation
#### performing same operation on multiple things

In [68]:
#numpy is much faster than python that's why when datatype is an ndarray use numpy's methods

In [69]:
import random
large_array= [random.randint(0,100) for i in range(10000)]
len(large_array)

10000

In [70]:
# syntax starting with % sign are magic methods
%timeit np.sum(large_array)
%timeit sum(large_array)

1.27 ms ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
148 µs ± 8.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [71]:
massive_array = np.random.rand(10000)

In [72]:
massive_array[:4]

array([0.89603839, 0.63892108, 0.89155444, 0.68005557])

In [73]:
%timeit np.sum(massive_array)
%timeit sum(massive_array)

18 µs ± 1.67 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.31 ms ± 83.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [74]:
np.mean(a1)

2.0

In [75]:
np.max(a1)

3

In [76]:
np.min(a1)

1

In [77]:
np.var(a1)

0.6666666666666666

In [78]:
np.std(a1)

0.816496580927726

In [79]:
np.sqrt(np.var(a1))

0.816496580927726

## Reshaping and Transposing

In [80]:
a2*a7
a2.shape

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [81]:
#lets reshape a2 to make it 3 dimensional

In [82]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [83]:
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped * a7

array([[[  0,   6,  19],
        [ 28,  20,  38],
        [ 24,  39,   6]],

       [[ 12,   8,  44],
        [ 65,  80,  40],
        [ 48, 114,  48]]])

### Transpose

In [84]:
# transpose only shuffles the dimensions

In [85]:
a2.shape

(2, 3)

In [86]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
a2.T.shape

(3, 2)

## Dot product vs element wise multiplication


In [88]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(2,3))
mat2 = np.random.randint(10,size = (2,3))

In [89]:
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9]]),
 array([[3, 5, 2],
        [4, 7, 6]]))

In [90]:
# This is the element wise multiplication 
np.multiply(mat1,mat2)

array([[15,  0,  6],
       [12, 49, 54]])

In [91]:
#dot product

In [92]:
np.dot(mat1,mat2)
#Here transpose is going to be used

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [93]:
mat3 = np.dot(mat1,mat2.T)

In [94]:
mat3

array([[ 21,  38],
       [ 62, 115]])

## Peanut butter sales practical example

In [95]:
np.random.seed(0)
weakly_sales = np.random.randint(20,size=(5,3))
# I want sales no more than 20 and there are 5 days and 3 varieties of butter that i sell

In [96]:
weakly_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [97]:
import pandas as pd

In [98]:
weakly_sales_DF = pd.DataFrame(weakly_sales,index=["Mon","Tue","Wed","Thur","Fri"],columns=["Almond butter","Peanut butter","Cashew butter"])

In [99]:
weakly_sales_DF

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [100]:
Price = np.array([10,8,12])

In [101]:
Price_DF = pd.DataFrame(Price.reshape(1,3),index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])

In [102]:
Price_DF

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [103]:
Price_DF.shape,weakly_sales_DF.shape

((1, 3), (5, 3))

In [104]:
total_daily_amount = np.dot(weakly_sales_DF,Price_DF.T)

In [105]:
total_daily_amount

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [106]:
weakly_sales_DF["Total"] = total_daily_amount

In [107]:
weakly_sales_DF

Almond butter  Peanut butter  Cashew butter  Total
Mon              12             15              0    240
Tue               3              3              7    138
Wed               9             19             18    458
Thur              4              6             12    232
Fri               1              6              7    142

## comparing Numpy arrays

In [108]:
a1

array([1, 2, 3])

In [109]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
#returns elementwise comparison 
a1 == a2

SyntaxError: invalid syntax (<ipython-input-110-95f97e394aa4>, line 1)

In [111]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [112]:
a1<a2

array([[False, False, False],
       [ True,  True,  True]])

In [113]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting Arrays

In [114]:
random_array = np.random.randint(100,size=(4,5))
random_array

array([[87, 46, 88, 81, 37],
       [25, 77, 72,  9, 20],
       [80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29]])

In [115]:
# sorts on ascending basis
random_array.sort()

In [116]:
random_array

array([[37, 46, 81, 87, 88],
       [ 9, 20, 25, 72, 77],
       [47, 64, 69, 79, 80],
       [29, 49, 82, 88, 99]])

In [117]:
# sorts the indices ! here no sorting is being done because I have used .sort() earlier
random_array.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [118]:
#axis1 refers to columns.Row will be same but different columns. It shows where the minimum number's index is in each column
random_array.argmin(axis = 1)

array([0, 0, 0, 0], dtype=int64)

In [119]:
random_array.argmax(axis=1)

array([4, 4, 4, 4], dtype=int64)

## Breaking images pixels to numpy arrays

<img src="numpy_images\panda.png" />

In [120]:
from matplotlib.image import imread

In [121]:
pandas = imread("numpy_images/panda.png")

In [122]:
pandas.shape,pandas.ndim,pandas.size

((2330, 3500, 3), 3, 24465000)

<img src="numpy_images\dog-photo.png" /> 

In [123]:
dog_pixels = imread("numpy_images/dog-photo.png")

In [124]:
dog_pixels.shape,dog_pixels.size

((432, 575, 4), 993600)

In [125]:
dog_pixels[:10,:15,1]

array([[0.80784315, 0.8117647 , 0.8156863 , 0.827451  , 0.827451  ,
        0.8156863 , 0.8156863 , 0.81960785, 0.81960785, 0.8235294 ,
        0.8156863 , 0.8117647 , 0.79607844, 0.7921569 , 0.7921569 ],
       [0.8039216 , 0.8039216 , 0.80784315, 0.80784315, 0.80784315,
        0.80784315, 0.8117647 , 0.8156863 , 0.8156863 , 0.81960785,
        0.8156863 , 0.80784315, 0.8       , 0.79607844, 0.79607844],
       [0.8       , 0.8039216 , 0.80784315, 0.8       , 0.8       ,
        0.8039216 , 0.8039216 , 0.8117647 , 0.8117647 , 0.8117647 ,
        0.8117647 , 0.80784315, 0.80784315, 0.8       , 0.79607844],
       [0.8039216 , 0.81960785, 0.83137256, 0.8235294 , 0.8156863 ,
        0.8117647 , 0.8117647 , 0.8156863 , 0.8117647 , 0.8039216 ,
        0.8039216 , 0.80784315, 0.8117647 , 0.8039216 , 0.8       ],
       [0.80784315, 0.81960785, 0.8352941 , 0.8392157 , 0.827451  ,
        0.81960785, 0.81960785, 0.81960785, 0.8156863 , 0.80784315,
        0.80784315, 0.8117647 , 0.8156863 , 